<a href="https://colab.research.google.com/github/avanegasp/Google_Colab/blob/main/Valores_nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [5]:
dicc = {'col1':[1,2,3,np.nan],
 'col2':[4,np.nan,6,7],
 'col3':['a','b','c',None]}

In [6]:
df = pd.DataFrame(dicc)

df

   col1  col2  col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [7]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [8]:
df.isnull()*1

   col1  col2  col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [9]:
df.fillna('Missing')

      col1     col2     col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [10]:
df.fillna(df.mean())

<ipython-input-10-a2478f315f9e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())

   col1      col2  col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [11]:
df.interpolate()

   col1  col2  col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [12]:
df.dropna()

   col1  col2 col3
0   1.0   4.0    a
2   3.0   6.0    c